=== bpmn-io/form-js/packages/form-json-schema/src/index.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://niklaskiefer.de/schema/form-js/1.0",
  "title": "form-js JSON Schema",
  "type": "object",
  "allOf": [
    {
      "$ref": "src/defs/rules/rules-default.json"
    }
  ],
  "properties": {
    "type": {
      "$id": "#/type",
      "description": "The type of a form.",
      "type": "string",
      "const": "default"
    },
    "id": {
      "$id": "#/id",
      "description": "The id of a form.",
      "type": "string"
    },
    "schemaVersion": {
      "$id": "#/schemaVersion",
      "description": "The schema version of a form",
      "type": "integer",
      "minimum": 1,
      "maximum": 20
    },
    "executionPlatform": {
      "$id": "#/executionPlatform",
      "description": "The target execution platform of a form",
      "type": "string"
    },
    "executionPlatformVersion": {
      "$id": "#/executionPlatformVersion",
      "description": "The target execution platform version of a form",
      "type": "string"
    },
    "versionTag": {
      "$id": "#/versionTag",
      "description": "The version tag of a form",
      "type": "string"
    },
    "exporter": {
      "$id": "#/exporter",
      "$ref": "src/defs/exporter.json"
    },
    "components": {
      "type": "array",
      "$id": "#/components",
      "description": "List of form fields.",
      "items": {
        "type": "object",
        "$ref": "src/defs/component.json",
        "$id": "#/component"
      },
      "allOf": [
        {
          "$ref": "src/defs/examples/components.json"
        }
      ]
    }
  },
  "required": ["type", "components"]
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/focusables.json
{
  "$schema": "../../../form-json-schema/resources/schema.json",
  "components": [
    {
      "label": "Number",
      "type": "number",
      "layout": {
        "row": "Row_0mj4ue9",
        "columns": null
      },
      "id": "number",
      "key": "number"
    },
    {
      "subtype": "date",
      "dateLabel": "Date",
      "label": "Date time",
      "type": "datetime",
      "layout": {
        "row": "Row_0pyh4s9",
        "columns": null
      },
      "id": "date",
      "key": "date"
    },
    {
      "subtype": "time",
      "label": "Date time",
      "type": "datetime",
      "layout": {
        "row": "Row_1bih132",
        "columns": null
      },
      "id": "time",
      "key": "time",
      "timeLabel": "Time",
      "timeSerializingFormat": "utc_offset",
      "timeInterval": 15
    },
    {
      "subtype": "datetime",
      "dateLabel": "Date",
      "label": "Date time",
      "type": "datetime",
      "layout": {
        "row": "Row_1j4nfzg",
        "columns": null
      },
      "id": "datetime",
      "key": "datetime",
      "timeLabel": "Time",
      "timeSerializingFormat": "utc_offset",
      "timeInterval": 15
    },
    {
      "label": "Text field",
      "type": "textfield",
      "layout": {
        "row": "Row_03ja9s1",
        "columns": null
      },
      "id": "textfield",
      "key": "textfield"
    },
    {
      "label": "Text area",
      "type": "textarea",
      "layout": {
        "row": "Row_1i5blqw",
        "columns": null
      },
      "id": "textarea",
      "key": "textarea"
    },
    {
      "label": "Checkbox",
      "type": "checkbox",
      "layout": {
        "row": "Row_1o5w06m",
        "columns": null
      },
      "id": "checkbox",
      "key": "checkbox"
    },
    {
      "values": [
        {
          "label": "Value",
          "value": "value"
        },
        {
          "label": "Value 2",
          "value": "value2"
        }
      ],
      "label": "Checklist",
      "type": "checklist",
      "layout": {
        "row": "Row_0lq7x9d",
        "columns": null
      },
      "id": "checklist",
      "key": "checklist"
    },
    {
      "values": [
        {
          "label": "Value",
          "value": "value"
        },
        {
          "label": "Value 2",
          "value": "value2"
        }
      ],
      "label": "Radio",
      "type": "radio",
      "layout": {
        "row": "Row_0o24b4q",
        "columns": null
      },
      "id": "radio",
      "key": "radio"
    },
    {
      "values": [
        {
          "label": "Value",
          "value": "value"
        }
      ],
      "label": "Select",
      "type": "select",
      "layout": {
        "row": "Row_1g6rfgk",
        "columns": null
      },
      "id": "select",
      "key": "select"
    },
    {
      "values": [
        {
          "label": "Value",
          "value": "value"
        }
      ],
      "label": "Select",
      "type": "select",
      "layout": {
        "row": "Row_1efssj7",
        "columns": null
      },
      "id": "searchableselect",
      "key": "searchableselect",
      "searchable": true
    },
    {
      "values": [
        {
          "label": "Value",
          "value": "value"
        },
        {
          "label": "Value 2",
          "value": "value2"
        }
      ],
      "label": "Tag list",
      "type": "taglist",
      "layout": {
        "row": "Row_04mnkm8",
        "columns": null
      },
      "id": "taglist",
      "key": "taglist"
    },
    {
      "action": "submit",
      "label": "Button",
      "type": "button",
      "layout": {
        "row": "Row_1vxa15p",
        "columns": null
      },
      "id": "button"
    }
  ],
  "type": "default",
  "id": "Form_13ywyw1",
  "exporter": {},
  "schemaVersion": 11
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/condition-external-variable.json
{
  "components": [
    {
      "key": "amount",
      "label": "Amount",
      "type": "number",
      "validate": {
        "min": 0,
        "max": 1000
      },
      "condition": "=externalVariable"
    },
    {
      "label": "Text Field",
      "type": "textfield",
      "id": "Field",
      "condition": "=amount > 2"
    }
  ],
  "type": "default",
  "id": "Form",
  "schemaVersion": 5
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/dynamic-list-table-filter-interaction.json
{
  "components": [
    {
      "label": "Table",
      "type": "table",
      "dataSource": "=riskEntries",
      "rowCount": 3,
      "id": "Table_1",
      "columns": [
        {
          "label": "Risk factor",
          "key": "risk"
        },
        {
          "label": "Name",
          "key": "name"
        },
        {
          "label": "Date",
          "key": "date"
        }
      ]
    },
    {
      "label": "Only show risk above",
      "type": "number",
      "id": "Number_2",
      "key": "onlyShowRiskAbove",
      "defaultValue": 5
    },
    {
      "components": [
        {
          "components": [
            {
              "text": "Risk factor: {{this.risk}}",
              "label": "Text view",
              "type": "text",
              "id": "Field_0kypubr"
            },
            {
              "label": "Risk factor",
              "type": "number",
              "id": "Number_1",
              "key": "risk"
            },
            {
              "label": "Name",
              "type": "textfield",
              "id": "TextField_1",
              "key": "name"
            },
            {
              "label": "Date",
              "type": "textfield",
              "id": "TextField_2",
              "key": "date"
            }
          ],
          "showOutline": true,
          "label": "Group",
          "type": "group",
          "id": "Group_1",
          "conditional": {
            "hide": "=this.risk <= onlyShowRiskAbove"
          }
        }
      ],
      "showOutline": true,
      "isRepeating": true,
      "allowAddRemove": true,
      "defaultRepetitions": 1,
      "label": "Dynamic list",
      "type": "dynamiclist",
      "id": "Dynamiclist_1",
      "path": "riskEntries",
      "nonCollapsedItems": null
    }
  ],
  "type": "default",
  "id": "Form_1je5j4d",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.4.0",
  "exporter": {
    "name": "Camunda Modeler",
    "version": "5.20.0"
  },
  "schemaVersion": 15
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/nested-complex-context.json
{
  "components": [
    {
      "label": "Test",
      "type": "textfield",
      "layout": {
        "row": "Row_06pau7i",
        "columns": null
      },
      "id": "Field_0naxgdd",
      "key": "a"
    },
    {
      "components": [
        {
          "text": "Flat: {{a}}\nParent: {{parent.a}}",
          "label": "Text view",
          "type": "text",
          "layout": {
            "row": "Row_0e00xn8",
            "columns": null
          },
          "id": "Field_03g3bvj"
        },
        {
          "label": "Test",
          "type": "textfield",
          "layout": {
            "row": "Row_0nqe5bi",
            "columns": null
          },
          "id": "Field_0oofqh4",
          "key": "b"
        },
        {
          "components": [
            {
              "text": "ParentThis: {{parent.this.b}}\nParent: {{parent.b}}\nGrandParent: {{parent.parent.a}}\nGrandParentThis: {{parent.parent.this.a}}",
              "label": "Text view",
              "type": "text",
              "layout": {
                "row": "Row_17ftgn9",
                "columns": null
              },
              "id": "Field_1bjzda6"
            }
          ],
          "showOutline": true,
          "isRepeating": true,
          "allowAddRemove": true,
          "defaultRepetitions": 1,
          "label": "Dynamic list",
          "type": "dynamiclist",
          "layout": {
            "row": "Row_0kn6m8y",
            "columns": null
          },
          "id": "Field_033ey1v",
          "path": "dynamiclist_lkkpkli"
        }
      ],
      "showOutline": true,
      "isRepeating": true,
      "allowAddRemove": true,
      "defaultRepetitions": 1,
      "label": "Dynamic list",
      "type": "dynamiclist",
      "layout": {
        "row": "Row_1d2g3ok",
        "columns": null
      },
      "id": "Field_1d4j6bh",
      "path": "list"
    }
  ],
  "$schema": "../../../form-json-schema/resources/schema.json",
  "type": "default",
  "id": "Form_1roxfho",
  "schemaVersion": 16
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/complex-expressions.json
{
  "components": [
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_12hk3xq",
      "key": "daysFactor",
      "expression": "=if tp.days = \"every_day\" then 365\n    else if tp.days = \"every_business_day\" then 250\n    else if tp.days = \"custom\" then tp.days_custom\n    else 0"
    },
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_0vjox1v",
      "key": "hoursFactor",
      "expression": "=if tp.hours = \"24_hours_per_day\" then 24\n    else if tp.hours = \"8_hours_per_day\" then 8\n    else if tp.hours = \"custom\" then tp.hours_custom\n    else 0"
    },
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_1i0ukso",
      "key": "numbers",
      "expression": "={\n  year: if tp.time_span = \"year\" then tp.pi\n  else if tp.time_span = \"quarter\" then tp.pi*4 \n  else if tp.time_span = \"month\" then tp.pi*12\n  else if tp.time_span = \"week\" then tp.pi*52.1429\n  else if tp.time_span = \"day\" then tp.pi*tp.daysFactor\n  else if tp.time_span = \"hour\" then tp.pi*tp.hoursFactor*tp.daysFactor\n  else if tp.time_span = \"minute\" then tp.pi*60*tp.hoursFactor*tp.daysFactor\n  else if tp.time_span = \"second\" then tp.pi*60*60*tp.hoursFactor*tp.daysFactor\n  else 0,\n  quarter: year/4,\n  month: year/12,\n  week: year/52.1429,\n  day: year/tp.daysFactor,\n  hour: day/tp.hoursFactor,\n  minute: hour/60,\n  second: minute/60,\n  year_tasks: year*tp.tasks,\n  quarter_tasks: quarter*tp.tasks,\n  month_tasks: month*tp.tasks,\n  week_tasks: week*tp.tasks,\n  day_tasks: day*tp.tasks,\n  hour_tasks: hour*tp.tasks,\n  minute_tasks: minute*tp.tasks,\n  second_tasks: second*tp.tasks\n}"
    },
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_0smrdqg",
      "key": "buffer_numbers",
      "expression": "={\n  factor: b.dynamic^b.period,\n  second_period: tp.numbers.second*factor,\n  second_tasks_period: tp.numbers.second_tasks*factor,\n  second_buffer: b.buffer*tp.numbers.second,\n  second_buffer_period: b.buffer*tp.numbers.second*factor,\n  second_buffer_tasks: second_buffer*tp.tasks,\n  second_buffer_tasks_period: second_buffer_tasks*factor,\n  day_period: tp.numbers.day*factor,\n  day_tasks_period: tp.numbers.day_tasks*factor,\n  day_buffer: b.buffer*tp.numbers.day,\n  day_buffer_period: b.buffer*tp.numbers.day*factor,\n  day_buffer_tasks: day_buffer*tp.tasks,\n  day_buffer_tasks_period: day_buffer_tasks*factor\n}"
    },
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_17s0dkj",
      "key": "diskSizes",
      "expression": "={\n  zeebe_logstream: 0.1 + 0.1*ds.payload + 0.25*ds.payload_base64,\n  operate: 0.1 + 0.1*ds.payload + 0.25*ds.payload_base64,\n  optimize: 0.03 + 0.25*ds.payload + 0.75*ds.payload_base64,\n  tasklist: 0.02 + 0.1*ds.payload + 0.25*ds.payload_base64,\n  total: zeebe_logstream + operate + optimize + tasklist,\n  zeebe_logstream_total: zeebe_logstream*tp.numbers.day*(ds.cycle_time+ds.zeebe_retention)*ds.zeebe_retention/1024/1024,\n  operate_total: operate*tp.numbers.day*(ds.cycle_time+ds.operate_retention)*ds.operate_retention/1024/1024,\n  optimize_total: optimize*tp.numbers.day*(ds.cycle_time+ds.optimize_retention)*ds.optimize_retention/1024/1024,\n  tasklist_total: tasklist*tp.numbers.day*(ds.cycle_time+ds.tasklist_retention)*ds.tasklist_retention/1024/1024,\n  total_total: zeebe_logstream_total + operate_total + optimize_total + tasklist_total,\n  zeebe_logstream_total_period: zeebe_logstream_total*b.buffer_numbers.factor,\n  operate_total_period: operate_total*b.buffer_numbers.factor,\n  optimize_total_period: optimize_total*b.buffer_numbers.factor,\n  tasklist_total_period: tasklist_total*b.buffer_numbers.factor,\n  total_total_period: total_total*b.buffer_numbers.factor\n}"
    }
  ],
  "type": "default",
  "id": "Form_1drkeef",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.5.0",
  "exporter": {
    "name": "Camunda Modeler",
    "version": "5.22.0"
  },
  "schemaVersion": 16
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/chain-expressions.json
{
  "components": [
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_staticValue",
      "key": "staticValue",
      "expression": "=10"
    },
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_exprA",
      "key": "exprA",
      "expression": "=staticValue + 10"
    },
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_exprB",
      "key": "exprB",
      "expression": "=exprA * 2"
    },
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_exprC",
      "key": "exprC",
      "expression": "=exprB + 10"
    }
  ],
  "type": "default",
  "id": "Form_non_cyclic_example",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.5.0",
  "exporter": {
    "name": "Camunda Modeler",
    "version": "5.22.0"
  },
  "schemaVersion": 16
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/cyclical-expressions.json
{
  "components": [
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_exprA",
      "key": "exprA",
      "expression": "=exprB + 10"
    },
    {
      "computeOn": "change",
      "type": "expression",
      "id": "Field_exprB",
      "key": "exprB",
      "expression": "=exprA * 2"
    }
  ],
  "type": "default",
  "id": "Form_cyclic_example",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.5.0",
  "exporter": {
    "name": "Camunda Modeler",
    "version": "5.22.0"
  },
  "schemaVersion": 16
}
