=== bpmn-io/form-js/packages/form-json-schema/src/index.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://niklaskiefer.de/schema/form-js/1.0",
  "title": "form-js JSON Schema",
  "type": "object",
  "allOf": [
    {
      "$ref": "src/defs/rules/rules-default.json"
    }
  ],
  "properties": {
    "type": {
      "$id": "#/type",
      "description": "The type of a form.",
      "type": "string",
      "const": "default"
    },
    "id": {
      "$id": "#/id",
      "description": "The id of a form.",
      "type": "string"
    },
    "schemaVersion": {
      "$id": "#/schemaVersion",
      "description": "The schema version of a form",
      "type": "integer",
      "minimum": 1,
      "maximum": 20
    },
    "executionPlatform": {
      "$id": "#/executionPlatform",
      "description": "The target execution platform of a form",
      "type": "string"
    },
    "executionPlatformVersion": {
      "$id": "#/executionPlatformVersion",
      "description": "The target execution platform version of a form",
      "type": "string"
    },
    "versionTag": {
      "$id": "#/versionTag",
      "description": "The version tag of a form",
      "type": "string"
    },
    "exporter": {
      "$id": "#/exporter",
      "$ref": "src/defs/exporter.json"
    },
    "components": {
      "type": "array",
      "$id": "#/components",
      "description": "List of form fields.",
      "items": {
        "type": "object",
        "$ref": "src/defs/component.json",
        "$id": "#/component"
      },
      "allOf": [
        {
          "$ref": "src/defs/examples/components.json"
        }
      ]
    }
  },
  "required": ["type", "components"]
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/readonly-expression.json
{
  "components": [
    {
      "key": "amount",
      "label": "Amount",
      "type": "number",
      "readonly": "=foo + bar = 2"
    },
    {
      "label": "Text Field",
      "type": "textfield",
      "id": "Field",
      "key": "text",
      "readonly": true
    }
  ],
  "type": "default",
  "id": "Form",
  "schemaVersion": 9
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/text.json
{
  "schemaVersion": 1,
  "exporter": {
    "name": "form-js (https://demo.bpmn.io)",
    "version": "0.1.0"
  },
  "components": [
    {
      "type": "text",
      "text": "# File an Invoice\n\n__Lorem ipsum dolor__ sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Arcu bibendum at [varius vel pharetra vel](http://foo) turpis nunc eget.\n\nAenean et tortor at risus. Ligula ullamcorper malesuada proin libero nunc consequat. Volutpat maecenas volutpat blandit aliquam etiam. Sodales neque sodales ut etiam sit amet nisl purus. Dictumst vestibulum rhoncus est pellentesque elit. \n\n# Another issue\n\n## Sub-heading\n\nArcu bibendum at varius vel pharetra vel turpis nunc eget.\n\n1. Scelerisque varius morbi enim nunc faucibus a. Senectus et netus et malesuada fames ac. \n2. Lorem sed risus ultricies tristique nulla aliquet. \n\nScelerisque felis imperdiet proin fermentum. \n\n* Purus semper eget duis at tellus at. \n* Imperdiet sed euismod nisi porta lorem mollis aliquam. \n* Dictum non consectetur a erat nam at lectus urna duis.\n\n\n## Images\n\n![some small image](https://via.placeholder.com/400x150)\n![Å¿ome big image](https://via.placeholder.com/1000x150)"
    }
  ],
  "type": "default"
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/documentPreview.json
{
  "components": [
    {
      "title": "Case {{case_id}} documents",
      "type": "documentPreview",
      "id": "Field_0wy8tws",
      "dataSource": "=my_documents",
      "endpointKey": "=my_documents_endpoint"
    }
  ],
  "$schema": "../../../form-json-schema/resources/schema.json",
  "type": "default",
  "id": "Form_1bd2k8m",
  "schemaVersion": 18
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/condition.json
{
  "components": [
    {
      "key": "amount",
      "label": "Amount",
      "type": "number",
      "validate": {
        "min": 0,
        "max": 1000
      }
    },
    {
      "label": "Text Field",
      "type": "textfield",
      "id": "Field",
      "key": "text",
      "condition": "=amount > 2"
    }
  ],
  "type": "default",
  "id": "Form",
  "schemaVersion": 5
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/ships-example.json
{
  "$schema": "../../../form-json-schema/resources/schema.json",
  "components": [
    {
      "text": "#### Ship Name:\n {{shipsForSale[item.name = selectedShip].name}}\n#### Ship Description: \n {{shipsForSale[item.name = selectedShip].description}}\n#### Ship Price: \n {{shipsForSale[item.name = selectedShip].purchasePrice}}\n#### Frame:\n {{shipsForSale[item.name = selectedShip].frame.name}}\n#### Reactor:\n {{shipsForSale[item.name = selectedShip].reactor.name}}\n#### Engine:\n {{shipsForSale[item.name = selectedShip].engine.name}}\n#### Moduels:\n {{shipsForSale[item.name = selectedShip].modules.name}}\n",
      "type": "text",
      "layout": {
        "row": "Row_1oxhkbh",
        "columns": null
      },
      "id": "Field_10y8si5",
      "conditional": {
        "hide": "=selectedShip = null"
      }
    }
  ],
  "schemaVersion": 9,
  "type": "default",
  "id": "Form_0ysvmoe"
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/hidden-fields-expression.json
{
  "components": [
    {
      "label": "a",
      "type": "checkbox",
      "key": "a"
    },
    {
      "label": "b",
      "type": "textfield",
      "key": "b"
    },
    {
      "label": "c",
      "type": "textfield",
      "key": "c",
      "conditional": {
        "hide": "=a"
      }
    },
    {
      "type": "image",
      "alt": "=b + c",
      "source": "https://"
    }
  ],
  "type": "default",
  "id": "Form_0z44jiv",
  "exporter": {},
  "schemaVersion": 6
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/nested-dynamic-list-required.json
{
  "$schema": "../../../form-json-schema/resources/schema.json",
  "components": [
    {
      "label": "Outer List",
      "type": "dynamiclist",
      "path": "outer",
      "id": "Outer_list",
      "isRepeating": true,
      "components": [
        {
          "label": "Inner List",
          "type": "dynamiclist",
          "path": "inner",
          "id": "Inner_list",
          "isRepeating": true,
          "components": [
            {
              "label": "Value",
              "type": "number",
              "key": "value",
              "id": "Nested_field",
              "validate": {
                "required": true
              }
            }
          ]
        }
      ]
    }
  ],
  "type": "default",
  "id": "Form_nested_required",
  "schemaVersion": 15
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/template-variable-complex.json
{
  "components": [
    {
      "text": "ConditionalExample: {{#if value > minimum}} Display conditionally {{display.subdisplay}} {{/if}}",
      "type": "text"
    },
    {
      "text": "NestedLoopExample: {{#loop orgs}} {{#loop members}} {{_parent_._parent_.external1.question}} {{/loop}} {{_parent_.external2}} {{/loop}}",
      "type": "text"
    },
    {
      "text": "AbiguousNamesExample: {{parent}} {{this}}",
      "type": "text"
    },
    {
      "text": "OutOfScopeExample: {{_parent_.child.child2}}",
      "type": "text"
    }
  ],
  "type": "default",
  "id": "Form",
  "schemaVersion": 6
}
