=== bpmn-io/form-js/packages/form-json-schema/src/index.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://niklaskiefer.de/schema/form-js/1.0",
  "title": "form-js JSON Schema",
  "type": "object",
  "allOf": [
    {
      "$ref": "src/defs/rules/rules-default.json"
    }
  ],
  "properties": {
    "type": {
      "$id": "#/type",
      "description": "The type of a form.",
      "type": "string",
      "const": "default"
    },
    "id": {
      "$id": "#/id",
      "description": "The id of a form.",
      "type": "string"
    },
    "schemaVersion": {
      "$id": "#/schemaVersion",
      "description": "The schema version of a form",
      "type": "integer",
      "minimum": 1,
      "maximum": 20
    },
    "executionPlatform": {
      "$id": "#/executionPlatform",
      "description": "The target execution platform of a form",
      "type": "string"
    },
    "executionPlatformVersion": {
      "$id": "#/executionPlatformVersion",
      "description": "The target execution platform version of a form",
      "type": "string"
    },
    "versionTag": {
      "$id": "#/versionTag",
      "description": "The version tag of a form",
      "type": "string"
    },
    "exporter": {
      "$id": "#/exporter",
      "$ref": "src/defs/exporter.json"
    },
    "components": {
      "type": "array",
      "$id": "#/components",
      "description": "List of form fields.",
      "items": {
        "type": "object",
        "$ref": "src/defs/component.json",
        "$id": "#/component"
      },
      "allOf": [
        {
          "$ref": "src/defs/examples/components.json"
        }
      ]
    }
  },
  "required": ["type", "components"]
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/filepicker.json
{
  "components": [
    {
      "label": "Root filepicker",
      "type": "filepicker",
      "id": "Field_0ix8ssu",
      "key": "root_filepicker",
      "accept": "=root_formats",
      "multiple": "=root_multiple"
    },
    {
      "label": "",
      "components": [
        {
          "label": "Group filepicker",
          "type": "filepicker",
          "id": "Field_1afqrsw",
          "key": "group_filepicker",
          "accept": "=group_formats",
          "multiple": "=group_multiple"
        }
      ],
      "showOutline": true,
      "type": "group",
      "id": "Field_1r2phwv",
      "path": "group_path"
    },
    {
      "label": "",
      "components": [
        {
          "label": "List filepicker",
          "type": "filepicker",
          "id": "Field_0ngzqh9",
          "key": "list_filepicker",
          "accept": "=list_formats",
          "multiple": "=list_multiple"
        }
      ],
      "showOutline": true,
      "isRepeating": true,
      "allowAddRemove": true,
      "defaultRepetitions": 1,
      "type": "dynamiclist",
      "id": "Field_1mfpipo",
      "path": "dynamiclist_path"
    }
  ],
  "type": "default",
  "id": "filepicker_form",
  "schemaVersion": 17
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/hidden-fields-conditional.json
{
  "components": [
    {
      "label": "a",
      "type": "checkbox",
      "key": "a"
    },
    {
      "label": "b",
      "type": "checkbox",
      "key": "b"
    },
    {
      "label": "c",
      "type": "checkbox",
      "key": "c",
      "conditional": {
        "hide": "=a"
      }
    },
    {
      "text": "# Text",
      "type": "text",
      "conditional": {
        "hide": "=b and c"
      }
    }
  ],
  "type": "default",
  "id": "Form_0jn1poe",
  "exporter": {},
  "schemaVersion": 6
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/dynamic-list-variables.json
{
  "$schema": "../../../form-json-schema/resources/schema.json",
  "schemaVersion": 15,
  "id": "Form_0zdct1y",
  "components": [
    {
      "components": [
        {
          "text": "{{this.key}}",
          "type": "text",
          "layout": {
            "row": "Row_0ieso1a",
            "columns": null
          },
          "id": "Field_0qywh6n"
        },
        {
          "label": "Number",
          "type": "number",
          "layout": {
            "row": "Row_0ieso1a",
            "columns": null
          },
          "id": "Field_16p25os",
          "key": "key"
        }
      ],
      "showOutline": true,
      "isRepeating": true,
      "allowAddRemove": true,
      "defaultRepetitions": 1,
      "label": "Dynamic list",
      "type": "dynamiclist",
      "layout": {
        "row": "Row_18s5yz0",
        "columns": null
      },
      "id": "Field_1dji6mu",
      "path": "list"
    }
  ],
  "type": "default"
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/complex-conditions.json
{
  "$schema": "../../../form-json-schema/resources/schema.json",
  "components": [
    {
      "label": "Complex display condition 1",
      "type": "textarea",
      "key": "c1",
      "conditional": {
        "hide": "={\nremainingAllowance: loanOptions.maxAllowance - loanOptions.currentlyUsed,\nrestAfterNewLoan: remainingAllowance - offeredAdditionalLoan\n        }.restAfterNewLoan < 0"
      }
    }
  ],
  "type": "default",
  "id": "Form_0jn1poe",
  "exporter": {},
  "schemaVersion": 12
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/expression-external-variable.json
{
  "components": [
    {
      "label": "An image",
      "source": "=logo",
      "type": "image"
    },
    {
      "label": "An image with alt text",
      "alt": "=alt",
      "type": "image"
    },
    {
      "label": "Another image",
      "alt": "This is just an image",
      "type": "image"
    }
  ],
  "type": "default",
  "id": "Form",
  "schemaVersion": 6
}

=== bpmn-io/form-js/packages/form-js-editor/test/spec/form-group.json
{
  "components": [
    {
      "id": "Textfield_1",
      "key": "invoiceNumber",
      "label": "Invoice Number",
      "type": "textfield",
      "layout": {
        "row": "Row_1",
        "columns": 16
      }
    },
    {
      "components": [
        {
          "label": "Text field",
          "type": "textfield",
          "layout": {
            "row": "Row_3",
            "columns": null
          },
          "id": "Textfield_2",
          "key": "textfield_2"
        }
      ],
      "showOutline": true,
      "label": "Group",
      "type": "group",
      "layout": {
        "row": "Row_2",
        "columns": null
      },
      "id": "Group_1"
    }
  ],
  "type": "default",
  "id": "Form_1",
  "schemaVersion": 11
}

=== bpmn-io/form-js/e2e/visual/fixtures/groups.json
{
  "schemaVersion": 8,
  "exporter": {
    "name": "Camunda Web Modeler",
    "version": "0de37f6"
  },
  "components": [
    {
      "type": "group",
      "id": "Group_1",
      "label": "Group 1",
      "showOutline": true,
      "components": [
        { 
          "type": "group",
          "id": "Group_2",
          "label": "Group 2",
          "showOutline": false,
          "components": [
            {
              "type": "textfield",
              "id": "Textfield_1",
              "label": "Textfield 1",
              "defaultValue": "Hello groups"
            },
            {
              "type": "checkbox",
              "id": "Checkbox_1",
              "label": "Checkbox 1",
              "defaultValue": true
            }
          ]
        }
      ]
    }
  ],
  "type": "default",
  "id": "form_id",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.2.0"
}

=== bpmn-io/form-js/packages/form-js-viewer/test/spec/template-variable.json
{
  "components": [
    {
      "text": "=myText",
      "type": "text"
    },
    {
      "text": "Just some text",
      "type": "text"
    },
    {
      "text": "Some templated text: {{greeting}} {{name}} {{#if showAge}} {{age}} {{/if}} {{#loop hobbies}} {{this}}: {{experience}} Y{{/loop}}",
      "type": "text"
    }
  ],
  "type": "default",
  "id": "Form",
  "schemaVersion": 6
}
